package io.jetform.core.enums;


public enum FieldType {

    TEXT, PASSWORD, CHECKBOX, NUMBER, HIDDEN, SELECT, DATE, FILE, TEL, EMAIL, RADIO, TEXT_AREA, URL, GENDER, MARITAL_STATUS, HYPER_LINK_TEXT, COUNTRY, STATES, TABLE, RANGE_SLIDER, RATTING, TOGGLE, FORM, ONE_TO_MANY
}